package bank;
// Generated Apr 24, 2015 10:35:45 AM by Hibernate Tools 3.6.0


import bank.BankBranch;
import java.math.BigDecimal;

/**
 * Bankadmin generated by hbm2java
 */
public class BankAdmin  implements java.io.Serializable {


     private Integer id;
     private BankBranch bankbranch;
     private String name;
     private String username;
     private String pass;
     private String address;
     private String city;
     private String state;

    public BankAdmin() {
    }

    public BankAdmin(Integer id, BankBranch bankbranch, String name, String username, String pass, String address, String city, String state) {
       this.id = id;
       this.bankbranch = bankbranch;
       this.name = name;
       this.username = username;
       this.pass = pass;
       this.address = address;
       this.city = city;
       this.state = state;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public BankBranch getBankbranch() {
        return this.bankbranch;
    }
    
    public void setBankbranch(BankBranch bankbranch) {
        this.bankbranch = bankbranch;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPass() {
        return this.pass;
    }
    
    public void setPass(String pass) {
        this.pass = pass;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public String getState() {
        return this.state;
    }
    
    public void setState(String state) {
        this.state = state;
    }




}


