package bank;
// Generated Apr 24, 2015 10:35:45 AM by Hibernate Tools 3.6.0


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Bankatm generated by hbm2java
 */
public class BankATM  implements java.io.Serializable {


     private Integer id;
     private BankBranch bankbranch;
     private BigDecimal till;
     private Set banktransactions = new HashSet(0);

    public BankATM() {
    }

	
    public BankATM(Integer id, BankBranch bankbranch, BigDecimal till) {
        this.id = id;
        this.bankbranch = bankbranch;
        this.till = till;
    }
    public BankATM(Integer id, BankBranch bankbranch, BigDecimal till, Set banktransactions) {
       this.id = id;
       this.bankbranch = bankbranch;
       this.till = till;
       this.banktransactions = banktransactions;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public BankBranch getBankbranch() {
        return this.bankbranch;
    }
    
    public void setBankbranch(BankBranch bankbranch) {
        this.bankbranch = bankbranch;
    }
    public BigDecimal getTill() {
        return this.till;
    }
    
    public void setTill(BigDecimal till) {
        this.till = till;
    }
    public Set getBanktransactions() {
        return this.banktransactions;
    }
    
    public void setBanktransactions(Set banktransactions) {
        this.banktransactions = banktransactions;
    }




}


