package bank;
// Generated Apr 21, 2015 10:00:28 PM by Hibernate Tools 3.6.0

import java.util.HashSet;
import java.util.Set;

/**
 * Bankcustomer generated by hbm2java
 */
public class BankCustomer implements java.io.Serializable {

    private Integer id;
    private String name;
    private String email;
    private String address;
    private String city;
    private String state;
    private Integer active;
    private Set bankaccounts = new HashSet(0);
    

    public BankCustomer() {
    }

    public BankCustomer(Integer id, String name, String address) {
        this.id = id;
        this.name = name;
        this.address = address;
        this.active = 1;
    }

    public BankCustomer(Integer id, String name, String email, String address, String city, String state) {
        this.id = id;
        this.name = name;
        this.email = email;
        this.address = address;
        this.city = city;
        this.state = state;
        this.active = 1;
    }

    public BankCustomer(Integer id, String name, String email, String address, String city, String state, Set bankaccounts) {
        this.id = id;
        this.name = name;
        this.email = email;
        this.address = address;
        this.city = city;
        this.state = state;
        this.bankaccounts = bankaccounts;
        this.active = 1;
    }

    
    /**
     * @param acct BankAccount to add to bankaccounts set
     * @return true if add succeeded, else false
     */
    public boolean addBankAccount(BankAccount acct) {
        return this.getBankaccounts().add(acct);
    }

    /**
     * @param acct BankAccount to remove from the bankaccounts set
     * @return true if removal succeeded, else false
     */
    public boolean removeBankAccount(BankAccount acct) {
        return this.getBankaccounts().remove(acct);
    }

    /**
     * @return the active
     */
    public Integer isActive() {
        return active;
    }

    /**
     * @param active the active to set
     */
    public void setActive(Integer active) {
        this.active = active;
    }

    /**
     * @return the id
     */
    public Integer getId() {
        return id;
    }

    /**
     * @param id the id to set
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * @return the name
     */
    public String getName() {
        return name;
    }

    /**
     * @param name the name to set
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * @return the email
     */
    public String getEmail() {
        return email;
    }

    /**
     * @param email the email to set
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * @return the address
     */
    public String getAddress() {
        return address;
    }

    /**
     * @param address the address to set
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * @return the city
     */
    public String getCity() {
        return city;
    }

    /**
     * @param city the city to set
     */
    public void setCity(String city) {
        this.city = city;
    }

    /**
     * @return the state
     */
    public String getState() {
        return state;
    }

    /**
     * @param state the state to set
     */
    public void setState(String state) {
        this.state = state;
    }

    /**
     * @return the bankaccounts
     */
    public Set getBankaccounts() {
        return bankaccounts;
    }

    /**
     * @param bankaccounts the bankaccounts to set
     */
    public void setBankaccounts(Set bankaccounts) {
        this.bankaccounts = bankaccounts;
    }

}
