package bank;
// Generated Apr 24, 2015 10:35:45 AM by Hibernate Tools 3.6.0


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Bankaccount generated by hbm2java
 */
public class BankAccount  implements java.io.Serializable {


     private Integer accountid;
     private BankCustomer bankcustomer;
     private BigDecimal balance;
     private String pin;
     private String cardnumber;
     private Set banktransactions = new HashSet(0);

    public BankAccount() {
    }

	
    public BankAccount(Integer accountid, BankCustomer bankcustomer, BigDecimal balance, String pin, String cardnumber) {
        this.accountid = accountid;
        this.bankcustomer = bankcustomer;
        this.balance = balance;
        this.pin = pin;
        this.cardnumber = cardnumber;
    }
    public BankAccount(Integer accountid, BankCustomer bankcustomer, BigDecimal balance, String pin, String cardnumber, Set banktransactions) {
       this.accountid = accountid;
       this.bankcustomer = bankcustomer;
       this.balance = balance;
       this.pin = pin;
       this.cardnumber = cardnumber;
       this.banktransactions = banktransactions;
    }
   
    public Integer getAccountid() {
        return this.accountid;
    }
    
    public void setAccountid(Integer accountid) {
        this.accountid = accountid;
    }
    public BankCustomer getBankcustomer() {
        return this.bankcustomer;
    }
    
    public void setBankcustomer(BankCustomer bankcustomer) {
        this.bankcustomer = bankcustomer;
    }
    public BigDecimal getBalance() {
        return this.balance;
    }
    
    public void setBalance(BigDecimal balance) {
        this.balance = balance;
    }
    public String getPin() {
        return this.pin;
    }
    
    public void setPin(String pin) {
        this.pin = pin;
    }
    public String getCardnumber() {
        return this.cardnumber;
    }
    
    public void setCardnumber(String cardnumber) {
        this.cardnumber = cardnumber;
    }
    public Set getBanktransactions() {
        return this.banktransactions;
    }
    
    public void setBanktransactions(Set banktransactions) {
        this.banktransactions = banktransactions;
    }




}


