package bank;
// Generated Apr 24, 2015 10:35:45 AM by Hibernate Tools 3.6.0


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Bankbranch generated by hbm2java
 */
public class BankBranch  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String address;
     private String city;
     private String state;
     private Set bankadmins = new HashSet(0);
     private Set bankatms = new HashSet(0);

    public BankBranch() {
    }

	
    public BankBranch(Integer id, String name, String address, String city, String state) {
        this.id = id;
        this.name = name;
        this.address = address;
        this.city = city;
        this.state = state;
    }
    public BankBranch(Integer id, String name, String address, String city, String state, Set bankadmins, Set bankatms) {
       this.id = id;
       this.name = name;
       this.address = address;
       this.city = city;
       this.state = state;
       this.bankadmins = bankadmins;
       this.bankatms = bankatms;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public String getState() {
        return this.state;
    }
    
    public void setState(String state) {
        this.state = state;
    }
    public Set getBankadmins() {
        return this.bankadmins;
    }
    
    public void setBankadmins(Set bankadmins) {
        this.bankadmins = bankadmins;
    }
    public Set getBankatms() {
        return this.bankatms;
    }
    
    public void setBankatms(Set bankatms) {
        this.bankatms = bankatms;
    }




}


